const level = [
  // {
  //   background: 'skatertux/images/backgrounds/semi_arctic.jpg',
  //   obstacles:[{type:'example',spawn_time:2000}],
  // },
  {
  background: 'skatertux/images/backgrounds/semi_arctic.jpg',
  run_time: 30000,
  run_distance: 7200,
  obstacles:[
    // {type:'sleeping_fox', spawn_distance:48, y:-1},
  	{type:'iceblock', spawn_distance:831, y:0},
  	{type:'snow', spawn_distance:1759, y:0},
  	{type:'icecube', spawn_distance:2449, y:0},
  	{type:'icecube', spawn_distance:2537, y:0},
  	{type:'icecube', spawn_distance:2631, y:0},
  	{type:'icecube', spawn_distance:2723, y:0},
  	{type:'snow', spawn_distance:3396, y:-3},
  	{type:'snow', spawn_distance:3999, y:-4},
  	{type:'icecube', spawn_distance:4470, y:-3},
  	{type:'icecube', spawn_distance:4570, y:-2},
  	{type:'icecube', spawn_distance:4802, y:-2},
  	{type:'icecube', spawn_distance:4896, y:-4},
  	{type:'owl', spawn_distance:5131, y:191},
  	{type:'radio', spawn_distance:5648, y:1},
  	{type:'snow', spawn_distance:6211, y:-2},
  	{type:'ramp_up', spawn_distance:6603, y:-1},
  	{type:'penguin', spawn_distance:7140, y:0},
  	{type:'penguin', spawn_distance:7233, y:1},
  	{type:'penguin', spawn_distance:7318, y:2},
  	{type:'penguin', spawn_distance:7361, y:18},
  	{type:'penguin', spawn_distance:7409, y:-1},

    ],
  },
  {
  background: 'skatertux/images/backgrounds/semi_arctic.jpg',
  run_time: 30000,
  run_distance: 5304,
  obstacles:[
    // {type:'iceblock', spawn_distance:50, y:-1},
  	{type:'snow', spawn_distance:619, y:-2},
  	{type:'ramp_up', spawn_distance:981, y:0},
  	{type:'snow_man', spawn_distance:1250, y:-1},
  	{type:'wodden_box', spawn_distance:1644, y:-2},
  	{type:'wodden_box', spawn_distance:1703, y:-1},
  	{type:'wodden_box', spawn_distance:1762, y:0},
  	{type:'wodden_box', spawn_distance:1820, y:-1},
  	{type:'big_wodden_box', spawn_distance:2032, y:-3},
  	{type:'big_wodden_box', spawn_distance:2112, y:-1},
  	{type:'big_wodden_box', spawn_distance:2191, y:0},
  	{type:'ramp_up', spawn_distance:2723, y:2},
  	{type:'big_icecube', spawn_distance:3039, y:0},
  	{type:'big_icecube', spawn_distance:3225, y:0},
  	{type:'owl', spawn_distance:3545, y:301},
  	{type:'radio', spawn_distance:3906, y:0},
  	{type:'ramp_up', spawn_distance:4265, y:0},
  	{type:'big_wodden_box', spawn_distance:4501, y:0},
  	{type:'big_wodden_box', spawn_distance:4581, y:78},
  	{type:'big_wodden_box', spawn_distance:4582, y:0},
  	{type:'big_wodden_box', spawn_distance:4660, y:80},
  	{type:'big_wodden_box', spawn_distance:4661, y:0},
  	{type:'big_wodden_box', spawn_distance:4741, y:1},
  	{type:'penguin', spawn_distance:5111, y:0},
  	{type:'penguin', spawn_distance:5217, y:11},
  	{type:'penguin', spawn_distance:5301, y:3},
  	{type:'penguin', spawn_distance:5421, y:12},
  	{type:'penguin', spawn_distance:5504, y:2},

    ],
  },
  {
    background: 'skatertux/images/backgrounds/semi_arctic.jpg',
    run_time: 34000,
    obstacles:[
      // {type:'snow',spawn_time:200},
      {type:'snow',spawn_time:2000},
      {type:'wodden_box',spawn_time:3500},
      {type:'wodden_box',spawn_time:6500},
      {type:'big_wodden_box',spawn_time:7500},
      {type:'iceblock',spawn_time:10500},
      {type:'owl',spawn_time:12500,y:200},
      {type:'ramp_up',spawn_time:15000},
      {type:'sleeping_fox',spawn_time:16000},
      {type:'wodden_box',spawn_time:19000},
      {type:'icecube',spawn_time:22000},
      {type:'icecube',spawn_time:23000, y: 50},
      {type:'icecube',spawn_time:24000, y: 100},
      {type:'icecube',spawn_time:25000, y: 150},
      {type:'mole',spawn_time:26000, y: -5},
      {type: 'penguin', spawn_time:28000},
      {type: 'penguin', spawn_time:28200},
      {type: 'penguin', spawn_time:28300},
      {type: 'penguin', spawn_time:28500},
      {type: 'penguin', spawn_time:28800},
      {type: 'penguin', spawn_time:29000},
      {type: 'penguin', spawn_time:29200},
      {type: 'penguin', spawn_time:29300},
      {type: 'penguin', spawn_time:29500},
      {type: 'penguin', spawn_time:30000},
      {type: 'penguin', spawn_time:30200},
      {type: 'penguin', spawn_time:31000},
      {type: 'penguin', spawn_time:31400},
      {type: 'penguin', spawn_time:32300},
      {type: 'penguin', spawn_time:32500},
      {type: 'penguin', spawn_time:33000},

    ],
  },
  {
  background: 'skatertux/images/backgrounds/semi_arctic.jpg',
  run_time: 30000,
  run_distance: 5000,
  obstacles:[
    {type:'radio', spawn_distance:583, y:0},
	{type:'iceblock', spawn_distance:927, y:0},
	{type:'icecube', spawn_distance:1347, y:0},
	{type:'big_icecube', spawn_distance:1537, y:0},
	{type:'big_icecube', spawn_distance:1911, y:0},
	{type:'icecube', spawn_distance:2286, y:0},
	{type:'owl', spawn_distance:2491, y:207},
	{type:'ramp_up', spawn_distance:2747, y:0},
	{type:'flying_platform', spawn_distance:3027, y:167},
	{type:'flying_platform', spawn_distance:3204, y:246},
	{type:'flying_platform', spawn_distance:3390, y:317},
	{type:'mole', spawn_distance:3603, y:-4},
	{type:'flying_platform', spawn_distance:3629, y:389},
	{type:'star', spawn_distance:3664, y:434},
	{type:'radio', spawn_distance:3817, y:1},
	{type:'flying_platform', spawn_distance:3916, y:408},
	{type:'wodden_box', spawn_distance:4024, y:0},
	{type:'wodden_box', spawn_distance:4086, y:0},
	{type:'flying_platform', spawn_distance:4188, y:411},
	{type:'cd', spawn_distance:4224, y:458},
	{type:'big_wodden_box', spawn_distance:4226, y:-1},
	{type:'penguin', spawn_distance:5120, y:6},
	{type:'penguin', spawn_distance:5247, y:5},
	{type:'penguin', spawn_distance:5320, y:12},
	{type:'penguin', spawn_distance:5412, y:4},
	{type:'penguin', spawn_distance:5566, y:8},

  ],
},
{
  background: 'skatertux/images/backgrounds/blue-middle.jpg',
  run_distance: 6700,
  obstacles:[
    {type:'sleeping_fox', spawn_distance:600, y:0},
	{type:'mole', spawn_distance:1059, y:-8},
	{type:'wodden_box', spawn_distance:1519, y:0},
	{type:'wodden_box', spawn_distance:1578, y:0},
	{type:'big_wodden_box', spawn_distance:1817, y:-1},
	{type:'wooden_block', spawn_distance:2096, y:0},
	{type:'wooden_block', spawn_distance:2192, y:0},
	{type:'ramp_up', spawn_distance:2288, y:100},
	{type:'wooden_block', spawn_distance:2289, y:0},
	{type:'wooden_block', spawn_distance:2387, y:0},
	{type:'flying_platform', spawn_distance:2653, y:225},
	{type:'flying_platform', spawn_distance:2777, y:225},
	{type:'firefly', spawn_distance:2948, y:272},
	{type:'flying_platform', spawn_distance:3093, y:278},
	{type:'owl', spawn_distance:3353, y:390},
	{type:'big_wodden_box', spawn_distance:3677, y:0},
	{type:'big_wodden_box', spawn_distance:3875, y:-1},
	{type:'sleeping_fox', spawn_distance:4376, y:0},
	{type:'firefly', spawn_distance:4779, y:238},
	{type:'firefly', spawn_distance:4891, y:145},
	{type:'firefly', spawn_distance:5001, y:216},
	{type:'wodden_box', spawn_distance:5241, y:-1},
	{type:'wooden_plattform', spawn_distance:5599, y:0},
	{type:'wooden_plattform', spawn_distance:5760, y:0},
	{type:'wooden_brick', spawn_distance:5816, y:31},
	{type:'wooden_plattform', spawn_distance:5919, y:0},
	{type:'wooden_plattform', spawn_distance:6079, y:1},
	{type:'wooden_block', spawn_distance:6300, y:-1},
	{type:'penguin', spawn_distance:6845, y:3},
	{type:'penguin', spawn_distance:6954, y:-6},
	{type:'penguin', spawn_distance:7048, y:5},
	{type:'penguin', spawn_distance:7100, y:20},
	{type:'penguin', spawn_distance:7163, y:-1},

  ],
},
{
  background: 'skatertux/images/backgrounds/blue-middle.jpg',
  run_distance: 7500,
  obstacles:[
    {type:'wooden_block', spawn_distance:300, y:0},
	{type:'wooden_plattform', spawn_distance:386, y:98},
	{type:'block', spawn_distance:534, y:0},
	{type:'wooden_block', spawn_distance:636, y:2},
	{type:'block', spawn_distance:986, y:0},
	{type:'water', spawn_distance:1086, y:0},
	{type:'star', spawn_distance:1124, y:174},
	{type:'block', spawn_distance:1216, y:-1},
	{type:'water', spawn_distance:1316, y:1},
	{type:'star', spawn_distance:1356, y:209},
	{type:'block', spawn_distance:1444, y:-5},
	{type:'water', spawn_distance:1543, y:1},
	{type:'star', spawn_distance:1575, y:185},
	{type:'block', spawn_distance:1671, y:-2},
	{type:'dizzy', spawn_distance:2425, y:2},
	{type:'old_brick', spawn_distance:2895, y:57},
	{type:'old_brick', spawn_distance:3130, y:140},
	{type:'old_brick', spawn_distance:3369, y:207},
	{type:'wooden_plattform', spawn_distance:3568, y:274},
	{type:'star', spawn_distance:3756, y:397},
	{type:'block', spawn_distance:3875, y:0},
	{type:'ramp_up', spawn_distance:4330, y:-1},
	{type:'water', spawn_distance:4527, y:0},
	{type:'coin', spawn_distance:4554, y:239},
	{type:'wooden_brick', spawn_distance:4656, y:0},
	{type:'owl', spawn_distance:4976, y:212},
	{type:'dizzy', spawn_distance:5287, y:0},
	{type:'ramp_up', spawn_distance:5662, y:81},
	{type:'big_wodden_box', spawn_distance:5663, y:0},
	{type:'big_wodden_box', spawn_distance:5792, y:0},
	{type:'flying_platform', spawn_distance:5955, y:251},
	{type:'flying_platform', spawn_distance:6150, y:388},
	{type:'flying_platform', spawn_distance:6359, y:528},
	{type:'star', spawn_distance:6396, y:574},
	{type:'flying_platform', spawn_distance:6625, y:532},
	{type:'star', spawn_distance:6653, y:579},
	{type:'flying_platform', spawn_distance:6815, y:397},
	{type:'flying_platform', spawn_distance:6998, y:278},
	{type:'penguin', spawn_distance:7516, y:3},
	{type:'penguin', spawn_distance:7586, y:-1},
	{type:'penguin', spawn_distance:7644, y:-1},
	{type:'penguin', spawn_distance:7728, y:-2},
	{type:'penguin', spawn_distance:7818, y:2},

  ],
},
{
  background: 'skatertux/images/backgrounds/blue-middle.jpg',
  run_distance: 6614,
  obstacles:[
    {type:'owl', spawn_distance:27, y:294},
	{type:'owl', spawn_distance:209, y:385},
	{type:'owl', spawn_distance:372, y:471},
	{type:'dizzy', spawn_distance:746, y:0},
	{type:'wodden_box', spawn_distance:1255, y:0},
	{type:'coin', spawn_distance:1379, y:2},
	{type:'wodden_box', spawn_distance:1478, y:-2},
	{type:'ramp_up', spawn_distance:1907, y:-3},
	{type:'ramp_up', spawn_distance:2100, y:95},
	{type:'block', spawn_distance:2102, y:-2},
	{type:'block', spawn_distance:2197, y:-1},
	{type:'star', spawn_distance:2337, y:299},
	{type:'flying_platform', spawn_distance:2416, y:269},
	{type:'flying_platform', spawn_distance:2587, y:401},
	{type:'flying_platform', spawn_distance:2775, y:484},
	{type:'owl', spawn_distance:2945, y:499},
	{type:'stones', spawn_distance:3024, y:0},
	{type:'flying_platform', spawn_distance:3039, y:489},
	{type:'firefly', spawn_distance:3188, y:513},
	{type:'firefly', spawn_distance:3209, y:473},
	{type:'stones', spawn_distance:3252, y:1},
	{type:'firefly', spawn_distance:3261, y:493},
	{type:'flying_platform', spawn_distance:3331, y:495},
	{type:'mole', spawn_distance:3577, y:-6},
	{type:'flying_platform', spawn_distance:3583, y:490},
	{type:'old_brick', spawn_distance:3822, y:398},
	{type:'wooden_plattform', spawn_distance:4058, y:458},
	{type:'star', spawn_distance:4130, y:505},
	{type:'wooden_plattform', spawn_distance:4215, y:458},
	{type:'star', spawn_distance:4326, y:498},
	{type:'wooden_plattform', spawn_distance:4373, y:456},
	{type:'dizzy', spawn_distance:4403, y:485},
	{type:'wooden_plattform', spawn_distance:4531, y:457},
	{type:'star', spawn_distance:4557, y:490},
	{type:'star', spawn_distance:4652, y:493},
	{type:'wooden_plattform', spawn_distance:4689, y:456},
	{type:'star', spawn_distance:4771, y:497},
	{type:'block', spawn_distance:5025, y:0},
	{type:'water', spawn_distance:5124, y:4},
	{type:'block', spawn_distance:5253, y:1},
	{type:'ramp_up', spawn_distance:5776, y:-2},
	{type:'block', spawn_distance:6072, y:3},
	{type:'coin', spawn_distance:6265, y:203},
	{type:'penguin', spawn_distance:6637, y:-3},
	{type:'penguin', spawn_distance:6768, y:-2},
	{type:'penguin', spawn_distance:6903, y:4},
	{type:'penguin', spawn_distance:7039, y:-3},
	{type:'penguin', spawn_distance:7114, y:-3},
  ],
},
{
  background: 'skatertux/images/backgrounds/blue-middle.jpg',
  run_distance: 6243,
  obstacles:[
    {type:'ramp_up', spawn_distance:300, y:0},
	{type:'ramp_up', spawn_distance:491, y:94},
	{type:'block', spawn_distance:498, y:-2},
	{type:'block', spawn_distance:598, y:-2},
	{type:'ramp_up', spawn_distance:674, y:190},
	{type:'block', spawn_distance:693, y:92},
	{type:'block', spawn_distance:700, y:2},
	{type:'block', spawn_distance:781, y:93},
	{type:'block', spawn_distance:788, y:3},
	{type:'water', spawn_distance:887, y:0},
	{type:'flying_platform', spawn_distance:990, y:333},
	{type:'star', spawn_distance:1016, y:374},
	{type:'wooden_brick', spawn_distance:1018, y:1},
	{type:'wooden_plattform', spawn_distance:1188, y:443},
	{type:'wooden_plattform', spawn_distance:1345, y:443},
	{type:'dizzy', spawn_distance:1379, y:470},
	{type:'wooden_brick', spawn_distance:1442, y:0},
	{type:'wooden_plattform', spawn_distance:1502, y:442},
	{type:'water', spawn_distance:1504, y:3},
	{type:'wooden_block', spawn_distance:1634, y:2},
	{type:'wooden_plattform', spawn_distance:1779, y:443},
	{type:'wooden_plattform', spawn_distance:2015, y:456},
	{type:'wooden_plattform', spawn_distance:2251, y:484},
	{type:'mole', spawn_distance:2289, y:-4},
	{type:'wooden_plattform', spawn_distance:2564, y:455},
	{type:'coin', spawn_distance:2568, y:488},
	{type:'coin', spawn_distance:2623, y:486},
	{type:'coin', spawn_distance:2677, y:488},
	{type:'firefly', spawn_distance:2867, y:581},
	{type:'firefly', spawn_distance:2942, y:522},
	{type:'firefly', spawn_distance:3004, y:559},
	{type:'big_wodden_box', spawn_distance:3358, y:0},
	{type:'ramp_up', spawn_distance:3402, y:80},
	{type:'big_wodden_box', spawn_distance:3438, y:0},
	{type:'big_wodden_box', spawn_distance:3520, y:0},
	{type:'big_wodden_box', spawn_distance:3599, y:0},
	{type:'big_wodden_box', spawn_distance:3600, y:80},
	{type:'star', spawn_distance:3646, y:270},
	{type:'big_wodden_box', spawn_distance:3679, y:0},
	{type:'big_wodden_box', spawn_distance:3679, y:80},
	{type:'big_wodden_box', spawn_distance:3761, y:0},
	{type:'big_wodden_box', spawn_distance:3840, y:-1},
	{type:'mole', spawn_distance:3990, y:-5},
	{type:'sleeping_fox', spawn_distance:4554, y:-1},
	{type:'wooden_block', spawn_distance:5218, y:0},
	{type:'wooden_block', spawn_distance:5315, y:2},
	{type:'wooden_block', spawn_distance:5318, y:100},
	{type:'wooden_plattform', spawn_distance:5525, y:295},
	{type:'star', spawn_distance:5578, y:335},
	{type:'wooden_plattform', spawn_distance:5816, y:295},
	{type:'star', spawn_distance:5870, y:338},
	{type:'penguin', spawn_distance:6335, y:1},
	{type:'penguin', spawn_distance:6459, y:5},
	{type:'penguin', spawn_distance:6615, y:0},
	{type:'penguin', spawn_distance:6671, y:-1},
	{type:'penguin', spawn_distance:6743, y:-1},

  ],
},
{
  background: 'skatertux/images/backgrounds/blue-middle.jpg',
  run_distance: 6126,
  obstacles:[
    {type:'bg_tree', spawn_distance: 50, y:-1},
	{type:'wodden_box', spawn_distance:300, y:0},
	{type:'wodden_box', spawn_distance:460, y:0},
	{type:'flying_platform', spawn_distance:921, y:65},
	{type:'water', spawn_distance:936, y:-19},
	{type:'flying_platform', spawn_distance:1142, y:135},
	{type:'flying_platform', spawn_distance:1383, y:215},
	{type:'walking_tree', spawn_distance:1415, y:3},
	{type:'star', spawn_distance:1547, y:296},
	{type:'wooden_brick', spawn_distance:1607, y:176},
	{type:'igel', spawn_distance:1630, y:0},
	{type:'wooden_brick', spawn_distance:1770, y:-10},
	{type:'water', spawn_distance:1833, y:-10},
	{type:'wooden_brick', spawn_distance:1962, y:-8},
	{type:'igel', spawn_distance:2070, y:0},
	{type:'walking_tree', spawn_distance:2506, y:0},
	{type:'wooden_plattform', spawn_distance:2507, y:74},
	{type:'cd', spawn_distance:2529, y:111},
	{type:'radio', spawn_distance:2576, y:3},
	{type:'cd', spawn_distance:2597, y:110},
	{type:'walking_tree', spawn_distance:2644, y:0},
	{type:'block', spawn_distance:3044, y:0},
	{type:'ramp_up', spawn_distance:3418, y:-5},
	{type:'bg_tree', spawn_distance:3492, y:0},
	{type:'cd', spawn_distance:3667, y:151},
	{type:'wooden_plattform', spawn_distance:4325, y:75},
	{type:'star', spawn_distance:4376, y:117},
	{type:'wooden_brick', spawn_distance:4532, y:62},
	{type:'wooden_plattform', spawn_distance:4598, y:63},
	{type:'wooden_plattform', spawn_distance:4784, y:123},
	{type:'coin', spawn_distance:4836, y:191},
	{type:'wooden_plattform', spawn_distance:5006, y:184},
	{type:'star', spawn_distance:5074, y:239},
	{type:'wooden_plattform', spawn_distance:5223, y:238},
	{type:'cd', spawn_distance:5262, y:274},
	{type:'wooden_plattform', spawn_distance:5428, y:305},
	{type:'penguin', spawn_distance:6249, y:4},
	{type:'penguin', spawn_distance:6414, y:-1},
	{type:'penguin', spawn_distance:6515, y:14},
	{type:'penguin', spawn_distance:6726, y:2},

  ],
},
{
  background: 'skatertux/images/backgrounds/semi_arctic.jpg',
  run_distance: 6377,
  obstacles:[
    {type:'iceblock', spawn_distance:300, y:0},
	{type:'star', spawn_distance:321, y:125},
	{type:'owl', spawn_distance:481, y:321},
	{type:'iceblock', spawn_distance:665, y:0},
	{type:'star', spawn_distance:680, y:137},
	{type:'iceblock', spawn_distance:1020, y:0},
	{type:'star', spawn_distance:1034, y:129},
	{type:'snow', spawn_distance:1372, y:0},
	{type:'snow', spawn_distance:1774, y:0},
	{type:'icecube', spawn_distance:2150, y:0},
	{type:'big_icecube', spawn_distance:2361, y:-2},
	{type:'flying_platform', spawn_distance:2695, y:245},
	{type:'flying_platform', spawn_distance:2923, y:337},
	{type:'flying_platform', spawn_distance:3207, y:456},
	{type:'star', spawn_distance:3244, y:501},
	{type:'igel', spawn_distance:3255, y:0},
	{type:'flying_platform', spawn_distance:3462, y:466},
	{type:'coin', spawn_distance:3494, y:515},
	{type:'flying_platform', spawn_distance:3575, y:466},
	{type:'coin', spawn_distance:3606, y:516},
	{type:'flying_platform', spawn_distance:3826, y:474},
	{type:'star', spawn_distance:3862, y:521},
	{type:'star', spawn_distance:4026, y:448},
	{type:'wodden_box', spawn_distance:4036, y:0},
	{type:'wodden_box', spawn_distance:4093, y:0},
	{type:'wodden_box', spawn_distance:4151, y:0},
	{type:'snow_man', spawn_distance:4241, y:0},
	{type:'star', spawn_distance:4250, y:155},
	{type:'icecube', spawn_distance:4540, y:0},
	{type:'big_icecube', spawn_distance:4764, y:-6},
	{type:'wodden_box', spawn_distance:4954, y:193},
	{type:'big_icecube', spawn_distance:4958, y:-5},
	{type:'wodden_box', spawn_distance:5012, y:193},
	{type:'snow_man', spawn_distance:5098, y:194},
	{type:'star', spawn_distance:5108, y:359},
	{type:'big_icecube', spawn_distance:5156, y:-5},
	{type:'water', spawn_distance:5356, y:-1},
	{type:'cd', spawn_distance:5403, y:322},
	{type:'water', spawn_distance:5434, y:0},
	{type:'icecube', spawn_distance:5549, y:-44},
	{type:'penguin', spawn_distance:6454, y:24},
	{type:'penguin', spawn_distance:6533, y:3},
	{type:'penguin', spawn_distance:6649, y:-2},
	{type:'penguin', spawn_distance:6699, y:33},
	{type:'penguin', spawn_distance:6777, y:10},

  ],
},
{
  background: 'skatertux/images/backgrounds/blue-middle.jpg',
  run_time: 30000,
  run_distance: 6714,
  obstacles:[
    {type:'big_wodden_box', spawn_distance:516, y:-2},
	{type:'water', spawn_distance:574, y:-17},
	{type:'star', spawn_distance:640, y:185},
	{type:'ramp_up', spawn_distance:939, y:0},
	{type:'wooden_plattform', spawn_distance:1264, y:122},
	{type:'wooden_plattform', spawn_distance:1422, y:122},
	{type:'star', spawn_distance:1483, y:189},
	{type:'wooden_plattform', spawn_distance:1579, y:122},
	{type:'flying_platform', spawn_distance:1853, y:190},
	{type:'star', spawn_distance:1889, y:242},
	{type:'flying_platform', spawn_distance:2030, y:303},
	{type:'star', spawn_distance:2060, y:367},
	{type:'flying_platform', spawn_distance:2209, y:374},
	{type:'star', spawn_distance:2232, y:439},
	{type:'flying_platform', spawn_distance:2426, y:450},
	{type:'cd', spawn_distance:2461, y:489},
	{type:'wodden_box', spawn_distance:2506, y:0},
	{type:'radio', spawn_distance:3110, y:0},
	{type:'big_wodden_box', spawn_distance:3459, y:-5},
	{type:'wooden_plattform', spawn_distance:3518, y:75},
	{type:'big_wodden_box', spawn_distance:3652, y:-4},
	{type:'wooden_block', spawn_distance:3912, y:-3},
	{type:'water', spawn_distance:4010, y:-4},
	{type:'star', spawn_distance:4020, y:192},
	{type:'wooden_block', spawn_distance:4138, y:-3},
	{type:'ramp_up', spawn_distance:4442, y:-3},
	{type:'water', spawn_distance:4639, y:-20},
	{type:'star', spawn_distance:4698, y:180},
	{type:'ramp_up', spawn_distance:5041, y:-2},
	{type:'forest_log', spawn_distance:5267, y:4},
	{type:'forest_log', spawn_distance:5363, y:66},
	{type:'forest_log', spawn_distance:5448, y:133},
	{type:'forest_log', spawn_distance:5451, y:4},
	{type:'cd', spawn_distance:5469, y:195},
	{type:'cd', spawn_distance:5519, y:197},
	{type:'forest_log', spawn_distance:5545, y:65},
	{type:'cd', spawn_distance:5569, y:197},
	{type:'forest_log', spawn_distance:5637, y:6},
	{type:'penguin', spawn_distance:6374, y:2},
	{type:'penguin', spawn_distance:6449, y:-1},
	{type:'penguin', spawn_distance:6541, y:-22},
	{type:'penguin', spawn_distance:6569, y:35},
	{type:'penguin', spawn_distance:6638, y:1},
	{type:'penguin', spawn_distance:6714, y:-12},

  ],
},
]

const obstacle_types = {
  // example: {
  //   width: 56,
  //   height: 90,
  //   src: 'skatertux/images/obstacles/example.png'
  // },
  snow_man: {
    width: 56,
    height: 90,
    src: 'skatertux/images/obstacles/s_manbig_0.png',
    /*multisrc:{
      count:3,
      src: 'skatertux/images/obstacles/s_manbig_',
      ending: '.png',
      animation_time: 500,
    },
    */
  },
  stones: {
    width: 50,
    height: 50,
    src: 'skatertux/images/obstacles/stones.png'
  },
  sleeping_fox: {
    width: 80,
    height: 40,
    src: 'skatertux/images/obstacles/foxsleep.png',
    multisrc: {
      count: 10,
      base: 'skatertux/images/obstacles/foxsleep',
      ending: '.png',
      animation_time: 500,
    }
  },
  owl:{
    width: 64,
    height: 64,
    src: 'skatertux/images/obstacles/owl0.png',
    multisrc: {
      count: 6,
      base: 'skatertux/images/obstacles/owl',
      ending: '.png',
      animation_time: 500,
    }
  },
  firefly:{
    width: 64,
    height: 32,
    src: 'skatertux/images/obstacles/firefly0.png',
    multisrc: {
      count: 4,
      base: 'skatertux/images/obstacles/firefly',
      ending: '.png',
      animation_time: 300,
    }
  },
  mole:{
    width: 64,
    height: 64,
    src: 'skatertux/images/obstacles/m0.png',
    multisrc: {
      count: 13,
      base: 'skatertux/images/obstacles/m',
      ending: '.png',
      animation_time: 2000,
    },
  },
  dizzy:{
    width: 54,
    height: 64,
    src: 'skatertux/images/obstacles/dizzy-0.png',
    multisrc: {
      count: 3,
      base: 'skatertux/images/obstacles/dizzy-',
      ending: '.png',
      animation_time: 2000,
    },
  },
  igel:{
    width: 48,
    height: 32,
    src: 'skatertux/images/obstacles/igel-0.png',
    multisrc: {
      count: 3,
      base: 'skatertux/images/obstacles/igel-',
      ending: '.png',
      animation_time: 2000,
    },
  },
  walking_tree:{
    width: 70,
    height: 70,
    src: 'skatertux/images/obstacles/walkingtree0.png',
    multisrc: {
      count: 3,
      base: 'skatertux/images/obstacles/walkingtree',
      ending: '.png',
      animation_time: 2000,
    },
  },
  radio: {
    width: 64,
    height: 42,
    src: 'skatertux/images/obstacles/radio1.png',
    multisrc: {
      count: 3,
      base: 'skatertux/images/obstacles/radio',
      ending: '.png',
      animation_time: 300,
    },
  },
  iceblock: {
    width: 81,
    height: 46,
    src: 'skatertux/images/obstacles/iceblock.png'
  },
  snow: {
    width: 60,
    height: 40,
    src: 'skatertux/images/obstacles/snow.png'
  },
  icecube: {
    width: 100,
    height: 100,
    src: 'skatertux/images/obstacles/icecube.png',
    skateable: true,
  },
  big_icecube: {
    width:200,
    height:200,
    src: 'skatertux/images/obstacles/icecube.png',
    skateable: true,
  },
  wodden_box: {
    width: 60,
    height: 40,
    src: 'skatertux/images/obstacles/wodden_box.png',
    skateable: true,
  },
  big_wodden_box: {
    width: 80,
    height: 80,
    src: 'skatertux/images/obstacles/wodden_box.png',
    skateable: true,
  },
  flying_platform: {
    width: 120,
    height: 40,
    skateable: true,
    src: 'skatertux/images/obstacles/flying_platform-0.png',
    multisrc: {
      count: 4,
      base: 'skatertux/images/obstacles/flying_platform-',
      ending: '.png',
      animation_time: 500,
    }
  },
  icefloe: {
    width: 256,
    height: 44,
    src: 'skatertux/images/obstacles/icefloe.png',
    skateable: true,
  },
  icefloe_small: {
    width: 128,
    height: 44,
    src: 'skatertux/images/obstacles/icefloe_small.png',
    skateable: true,
  },
  old_brick: {
    width: 128,
    height: 32,
    src: 'skatertux/images/obstacles/oldbrick.png',
    skateable: true,
  },
  wooden_plattform: {
    width: 160,
    height: 32,
    src: 'skatertux/images/obstacles/wood-fivetiles.png',
    skateable: true,
  },
  wooden_brick: {
    width: 64,
    height: 32,
    src: 'skatertux/images/obstacles/wood-small.png',
    skateable: true,
  },
  wooden_block: {
    width: 100,
    height: 100,
    src: 'skatertux/images/obstacles/wood-tiny.png',
    skateable: true,
  },
  block: {
    width: 100,
    height: 100,
    src: 'skatertux/images/obstacles/block10.png',
    skateable: true,
  },
  water: {
    width: 128,
    height: 32,
    src: 'skatertux/images/obstacles/water-0.png',
    multisrc: {
      count: 8,
      base: 'skatertux/images/obstacles/water-',
      ending: '.png',
      animation_time: 600,
    },
  },
  antenna: {
    width: 64,
    height: 89,
    src: 'skatertux/images/obstacles/Antena2.png',
  },



  //special:
  //collectibles
  cd: {
    width: 50,
    height: 50,
    src: 'skatertux/images/obstacles/cd0.png',
    multisrc:{
      count: 5,
      base: 'skatertux/images/obstacles/cd',
      ending:'.png',
      animation_time: 300,
    },
    no_colision: true,
    collectible: true,
  },
  coin: {
    width: 50,
    height: 50,
    src: 'skatertux/images/obstacles/coin-0.png',
    multisrc:{
      count: 16,
      base: 'skatertux/images/obstacles/coin-',
      ending:'.png',
      animation_time: 1000,
    },
    no_colision: true,
    collectible: true,
  },
  star: {
    width: 50,
    height: 50,
    src: 'skatertux/images/obstacles/star0.png',
    multisrc:{
      count: 6,
      base: 'skatertux/images/obstacles/star',
      ending:'.png',
      animation_time: 1000,
    },
    no_colision: true,
    collectible: true,
  },
  air_flower: {
    width: 64,
    height: 64,
    src: 'skatertux/images/obstacles/air_flower-0.png',
    multisrc:{
      count: 4,
      base: 'skatertux/images/obstacles/air_flower-',
      ending:'.png',
      animation_time: 500,
    },
    no_colision: true,
    collectible: true,
  },
  //ramp:
  ramp_up:{
    width: 200,
    height: 100,
    src: 'skatertux/images/obstacles/rampup.png',
    ramp: true,
    upward: true,
  },
  //grind:
  branch_left:{
    width:250,
    height:51,
    src: 'skatertux/images/obstacles/branchleft.png',
    no_colision: true,
    grindable: true,
    path:{
      waypoints: [{x:0,y:25}, {x:250,y:25}],
      //route: [y1,y2,y3...]
    },
  },
  branch_left2:{
    width:270,
    height:85,
    src: 'skatertux/images/obstacles/branchleft2.png',
    no_colision: true,
    grindable: true,
    path:{
      waypoints: [{x:0,y:25}, {x:250,y:70}],
      //route: [y1,y2,y3...]
    },
  },
  branch_right:{
    width:250,
    height:51,
    src: 'skatertux/images/obstacles/branchleft.png',
    no_colision: true,
    grindable: true,
    path:{
      waypoints: [{x:0,y:25}, {x:250,y:25}],
      //route: [y1,y2,y3...]
    },
  },
  branch_right2:{
    width:270,
    height:85,
    src: 'skatertux/images/obstacles/branchleft2.png',
    no_colision: true,
    grindable: true,
    path:{
      waypoints: [{x:0,y:70}, {x:250,y:25}],
      //route: [y1,y2,y3...]
    },
  },
  forest_log:{
    width:192,
    height:64,
    src: 'skatertux/images/obstacles/forestlog.png',
    no_colision: true,
    grindable: true,
    path:{
      waypoints: [{x:0,y:64}, {x:192,y:64}],
      //route: [y1,y2,y3...]
    },
  },
  bg_library: {
    width: 417,
    height: 450,
    src: 'skatertux/images/library-big.png',
    no_colision: true,
    grindable: true,
    path:{
      waypoints: [{x:54,y:130}, {x:350,y:130}],
      //route: [y1,y2,y3...]
    },
  },
  //end goal:
  penguin: {
    width: 70,
    height: 100,
    src: 'skatertux/images/obstacles/penny.png',
    no_colision: true,
  },
  //no colision:
  bg_tree: {
    width: 500,
    height: 1000,
    src: 'skatertux/images/obstacles/foresttree.png',
    no_colision: true,
  },
  //animation-helper
  spark: {
    width: 50,
    height: 70,
    src: 'skatertux/images/obstacles/sparkle-0.png',
    multisrc: {
      count: 17,
      base: 'skatertux/images/obstacles/sparkle-',
      ending: '.png',
      animation_time: 1000,
      animation_count: 1,
    },
    no_colision: true,
  },
}

function create_ramp_up(){
  let ramparr = []
  let rampinc = obstacle_types.ramp_up.height / obstacle_types.ramp_up.width
  console.log(rampinc, obstacle_types.ramp_up.height, obstacle_types.ramp_up.width);
  for(let i=0;i<obstacle_types.ramp_up.width;i++){
    ramparr.push(i*rampinc)
  }
  obstacle_types.ramp_up.ramparr = ramparr
}
function create_paths(){
  let keys = Object.keys(obstacle_types)
  for(let ob=0;ob<keys.length;ob++){
    if(!obstacle_types[keys[ob]].path)continue;
    let path = obstacle_types[keys[ob]].path
    let ypoint = []
    for(let wp=0;wp<path.waypoints.length-1;wp++){
      let startpoint = path.waypoints[wp]
      let endpoint = path.waypoints[wp+1]
      let dify = endpoint.y - startpoint.y
      let len = endpoint.x - startpoint.x
      let difinc = dify/len
      for(let i=0;i<len;i++){
        ypoint[startpoint.x+i]=startpoint.y+(difinc*i)
      }
    }
    path.route=ypoint
  }
}


function create_multisrc(){
  let keys = Object.keys(obstacle_types)
  for(let i=0;i<keys.length;i++){
    if(!obstacle_types[keys[i]].multisrc)continue;
    let ms = obstacle_types[keys[i]].multisrc
    ms.frame_time = ms.animation_time / ms.count
  }
}
create_ramp_up()
create_multisrc()
create_paths()

function change_to_distances(){
  for(let i=0;i<level.length;i++){
    for(let ii=0;ii<level[i].obstacles.length;ii++){
      if(!level[i].obstacles[ii].spawn_distance){
        level[i].obstacles[ii].spawn_distance = level[i].obstacles[ii].spawn_time * game.tux.speed
      }
    }
  }
}
change_to_distances()
